# Generated by Django 5.2.6 on 2026-02-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("excelprojremakemainapp", "0002_cash_mailing_address_wire_transfer_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="Target_profit",
            field=models.FloatField(default=0, null=True),
        ),
    ]
